/**
 * Recipe id redirect map.
 *
 * When a recipe is renamed at the dataset level — typically because
 * its original title contained language we no longer want on the
 * site — its id changes. Anyone with a bookmark or a saved cookbook
 * entry pointing at the old id would 404. This module ships a small
 * map of old-id → new-id that the RecipePage checks before giving
 * up on a missing recipe, and redirects cleanly.
 *
 * The file public/recipe_redirects.json is generated by
 * scripts/patch_problematic_titles.py and can grow over time.
 */

const PUBLIC_URL = `${import.meta.env.BASE_URL}recipe_redirects.json`;

let cache: Record<string, string> | null = null;
let inflight: Promise<Record<string, string>> | null = null;

async function load(): Promise<Record<string, string>> {
  if (cache) return cache;
  if (inflight) return inflight;
  inflight = (async () => {
    try {
      const res = await fetch(PUBLIC_URL, { cache: 'force-cache' });
      if (!res.ok) {
        cache = {};
        return cache;
      }
      const data = await res.json();
      cache = (data && typeof data === 'object' ? data : {}) as Record<string, string>;
      return cache;
    } catch {
      cache = {};
      return cache;
    }
  })();
  return inflight;
}

/**
 * Returns the new id for a renamed recipe, or null if no redirect
 * exists. Safe to call before or after the library has loaded —
 * the map fetches lazily and caches.
 */
export async function resolveRedirect(oldId: string): Promise<string | null> {
  const map = await load();
  return map[oldId] ?? null;
}
